### PR TITLE
updated readme file with installation instructions and rewuirements

### PR DESCRIPTION
**Pull request by ikbenmacje**

### CODE REVIEW

**Comment by fieldOfView** [comment]
Are you sure Qt4 needs to be installed separately? Not so on windows...

**Comment by fieldOfView** [comment]
Also, as long as we're creating setup instructions, it's a good idea to include/point to the pyZOCP setup instructions.

**Comment by ikbenmacje** [comment]
My errors was more or les the following:

ImportError: dlopen(/Library/Python/2.6/site-packages/PySide/QtCore.so, 2): Library not loaded: QtCore.framework/Versions/4/QtCore
  Referenced from: /Library/Python/2.6/site-packages/PySide/QtCore.so
  Reason: image not found

Only for me it was not Python 2.6 but python 3.4.2. As far as I understood PySide was looking for Qt libraries that it could not find. Apparently it was searching for them at the wrong location?

So I tried:

export DYLD_LIBRARY_PATH="/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PySide/"

Which did not work so I figured that I needed to install Qt and then it worked immediately. See also: http://qt-project.org/forums/viewthread/9024

If someone else can reproduce the error and fix it in a different way then the readMe should be changed to include his/her solution until that time this is what I needed to do as a OSX user to get this to work on my machine.

I wil update the readme in my repository to point to the main zocp instructions..

**Comment by fieldOfView** [comment]
I found this which confirms that OSX is probably the only platform where you have to separately install Qt4:
https://github.com/PySide/pyside-setup/blob/master/README.rst
I did not have to install Qt4 on a clean Raspbian either.

**Comment by ikbenmacje** [comment]
I updated the readme to be more clear. However I am still missing instructions for Linux and Windows.

**Pull request merged**
