### PR TITLE
Integrate ZConfigManager

### PR DESCRIPTION
**Pull request by fieldOfView**
This pullrequest adds https://github.com/fieldofview/pyZConfigManager as a submodule. Using the Config Manager one can store and restore node configurations to/from disk. 

Node configurations consist of the full capability tree, including capability structure and data, as well as signal subscriptions between nodes. Note that ff a node has been restarted at some point, it will have a different UUID. In this case the configmanager will look for a replacement node by the same name.

pyZConfigManager can be used as a standalone command line utility, but it has been integrated in the Node Editor as Open/Save functionality.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Fixed a couple of rookie merge mistakes, thanks @ikbenmacje

**Comment by fieldOfView** [comment]
Note that https://github.com/fieldOfView/pyZConfigManager is introduced as a submodule. Be sure to get the files from this submodule when you checkout this branch to test.

```
git remote add fieldofview https://github.com/fieldOfView/pyZNodeEditor.git
git pull fieldofview
git checkout -b feature_configmanager
git submodule init
git submodule update
```

Or you can clone a fresh copy of the branch including the submodule like this:

```
git clone --recursive https://github.com/fieldOfView/pyZNodeEditor.git -b feature_configmanager
```

**Comment by sphaero** [comment]
Completely missed this one. I'm merging it. Is it an idea to move the configmanager to z25 community??

**Comment by fieldOfView** [comment]
I'll update the README to include submodule instructions. I have no problems with moving the configmanager to a z25 repo, or even moving it out of a submodule and into the nodeeditor repo. But it depends a little on if we like the approach I've taken.

I saw some mention of config management in your Pyre branch; lets discuss off-github.

**Comment by fieldOfView** [comment]
NB: I have some ideas to improve the configmanager (eg partial reads or writes including only subscriptions, or only certain (selected) nodes).

**Comment by sphaero** [comment]
Do yoy mean discuss it through the z25 mailinglists? I'm ok with doing it through github... z25 mailinglists are not public. 
In any way in regards to the config files the thing is it might look like a config file but in fact it is a language. The language describes the setup of nodes. This can be dynamic. But if we start with just having a fixed point in time description but in the back of our minds knowing it is a language...

Similarly as PureData. .PD files just consist of an object description and it's connections:

```
#X obj 4 373 tabread4~ \$1-grain-env;
#X obj 159 457 r \$0-mystart;
#X obj 144 513 tabread4~ \$1-source-array;
#X connect 0 0 1 0;
#X connect 0 0 7 0;
#X connect 1 0 26 0;
```

**Comment by fieldOfView** [comment]
> Do yoy mean discuss it through the z25 mailinglists?

I meant discuss it face-to-face on monday.

**Pull request merged**
